import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserfrontProvider } from "@userfront/next/client";
import { ReactNode } from "react";
import Header from "@luz-catalogue/app/_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserfrontProvider
          tenantId={process.env.NEXT_PUBLIC_USERFRONT_TENANT_ID}
          loginRedirect="/admin-dashboard"
          requireAuth
        >
          <Header />
          {children}
        </UserfrontProvider>
      </body>
    </html>
  );
}
